# Generated by Django 3.1.1 on 2020-09-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
